//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string Title { get; set; }
        public string ArticleContent { get; set; }
        public string CoverImage { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string Source { get; set; }
        public Nullable<int> ClickTimes { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Label { get; set; }
        public Nullable<int> AgreeTimes { get; set; }
        public Nullable<bool> Isdel { get; set; }
        public string Equipment { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> AgainstTimes { get; set; }
        public string SourceUrl { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
