//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public string ComContent { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public string ComEquipment { get; set; }
        public Nullable<System.DateTime> ComDate { get; set; }
        public string ComCity { get; set; }
        public string Jubao { get; set; }
        public Nullable<int> SupportTimes { get; set; }
        public Nullable<int> AgainstTimes { get; set; }
        public string Reply { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<bool> Isdel { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string TouristName { get; set; }
    }
}
