//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassageBoard
    {
        public int id { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public string PublisherIP { get; set; }
        public string MsgContent { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<bool> Isdel { get; set; }
        public string Equipment { get; set; }
        public string Reply { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
    }
}
