//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string NikName { get; set; }
        public string Email { get; set; }
        public string UserImage { get; set; }
        public string Weibo { get; set; }
        public string Note { get; set; }
        public Nullable<int> QQ { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> LoginDay { get; set; }
        public Nullable<bool> Isdel { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> LevelID { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
